Unset HAVE_SYSCTL for linux-noasm
This is needed to reland:
https://chromium-review.googlesource.com/c/chromium/src/+/2654206

Which was reverted due to the following error on Linux/MSAN:
[2915/61822] CC obj/third_party/ffmpeg/ffmpeg_internal/autorename_libavutil_cpu.o
FAILED: obj/third_party/ffmpeg/ffmpeg_internal/autorename_libavutil_cpu.o
/b/s/w/ir/cache/goma/client/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang -MMD -MF o...(too long)
In file included from ../../third_party/ffmpeg/libavutil/autorename_libavutil_cpu.c:2:
In file included from ../../third_party/ffmpeg/libavutil/cpu.c:44:
../../build/linux/debian_sid_amd64-sysroot/usr/include/x86_64-linux-gnu/sys/sysctl.h:21:2: error: "The <sys/sysctl.h> header is deprecated and will be removed." [-Werror,-W#warnings]

Bug: 1167405
Change-Id: Ifb47de41c3fd11cd4ac956b25c58ca314869e8c8
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/third_party/ffmpeg/+/2654248
Reviewed-by: Dale Curtis <dalecurtis@chromium.org>